extends: '@hamster-bot/eslint-config/typescript'

rules:
  # TypeScript would do this check so we don't need this.
  import/no-unresolved: off

ignorePatterns:
  - node_modules
  - lib
  - dist
  - coverage
  - docs
  - packages/*/node_modules
  - packages/*/dist
  - packages/*/coverage
  - packages/*/docs
  - external/**/*
